import { create } from 'zustand';
import { getApiHost } from '@/lib/apiBase';
import { apiFetch } from '@/lib/api';

function formatBytes(bytes: number | null | undefined): string {
  if (!bytes || bytes <= 0) return '—';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export type DeliverableType = 'docx' | 'xlsx' | 'pptx' | 'py';

export interface DeliverableItem {
  id: string;
  filename: string;
  type: DeliverableType;
  size_bytes: number;
  size_formatted: string;
  source_scenario: string;
  source_requirement: string;
  generating_model: string;
  generated_timestamp: string;
  sha256_hash: string;
  summary: string;
  key_metrics: { label: string; value: string }[];
  sop_citations: string[];
}

interface DeliverableState {
  deliverables: DeliverableItem[];
  selectedDeliverable: DeliverableItem | null;
  filterType: 'ALL' | DeliverableType;
  searchQuery: string;

  // Actions
  setFilterType: (type: 'ALL' | DeliverableType) => void;
  setSearchQuery: (query: string) => void;
  selectDeliverable: (id: string | null) => void;
  downloadDeliverable: (id: string) => Promise<void>;
  addDeliverableFromAgent: (filename: string, scenarioId: string, modelId: string) => void;
  fetchDiskDeliverables: () => Promise<void>;
}

export const useDeliverableStore = create<DeliverableState>((set, get) => ({
  deliverables: [],
  selectedDeliverable: null,
  filterType: 'ALL',
  searchQuery: '',

  setFilterType: (filterType) => set({ filterType }),
  setSearchQuery: (searchQuery) => set({ searchQuery }),

  selectDeliverable: (id) => {
    if (!id) {
      set({ selectedDeliverable: null });
      return;
    }
    const item = get().deliverables.find((d) => d.id === id) || null;
    set({ selectedDeliverable: item });
  },

  addDeliverableFromAgent: (identifierOrFilename: string, scenarioId: string, modelId: string) => {
    const cleanId = identifierOrFilename.replace(/^\/api\/files\/(download\/)?/, '').trim();
    if (!cleanId) return;

    get().fetchDiskDeliverables();

    const existing = get().deliverables.find(d => d.id === cleanId || d.filename.toLowerCase() === cleanId.toLowerCase());
    if (existing) return;

    let ext: DeliverableType = 'docx';
    let filename = cleanId;
    if (cleanId.includes('.')) {
      const parsedExt = cleanId.split('.').pop()?.toLowerCase();
      if (['docx', 'xlsx', 'pptx', 'py'].includes(parsedExt || '')) {
        ext = parsedExt as DeliverableType;
      }
    } else {
      filename = `${cleanId}.docx`;
    }

    const newItem: DeliverableItem = {
      id: cleanId,
      filename,
      type: ext,
      // Placeholder until the backend reports the real size/hash for this file.
      size_bytes: 0,
      size_formatted: '—',
      source_scenario: scenarioId,
      source_requirement: 'Production Deliverable',
      generating_model: modelId,
      generated_timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      sha256_hash: 'unavailable',
      summary: `Automated deliverable generated by ${modelId} for ${scenarioId}.`,
      key_metrics: [{ label: 'Status', value: 'AWAITING SERVER METADATA' }],
      // No invented source references: a citation is only shown when the
      // server supplied one. GET /api/files/list returns no `sop_citations`
      // field, so the previous default rendered "MRPL Standard Engineering
      // Reference" on every card as if it were a real citation.
      sop_citations: []
    };

    set(state => ({ deliverables: [newItem, ...state.deliverables] }));
  },

  fetchDiskDeliverables: async () => {
    try {
      const res = await apiFetch(`/api/files/list`);
      if (res.ok) {
        const data = await res.json();
        const rawList = data.files || data.deliverables || [];
        if (Array.isArray(rawList)) {
          const diskItems: DeliverableItem[] = rawList.map((f: any) => {
            const rawExt = (f.filename || '').split('.').pop()?.toLowerCase();
            const type = (f.file_type || rawExt || 'docx').toLowerCase() as DeliverableType;
            return {
              id: f.file_id || f.id || `deliv-${Date.now()}`,
              filename: f.filename || `deliverable_${f.file_id || 'unnamed'}.${type}`,
              type: (['docx', 'xlsx', 'pptx', 'py'].includes(type) ? type : 'docx') as DeliverableType,
              size_bytes: typeof f.size_bytes === 'number' ? f.size_bytes : 0,
              size_formatted: f.size_formatted || formatBytes(f.size_bytes),
              source_scenario: f.chat_id ? `Session: ${f.chat_id}` : (f.source_scenario || 'Refinery Output'),
              source_requirement: f.source_requirement || 'Generated Deliverable',
              // The backend does not record which model produced a file, so
              // report "unavailable" rather than naming a model that may not
              // have generated it.
              generating_model: f.generating_model || 'unavailable',
              generated_timestamp: f.created_at || f.generated_timestamp || new Date().toLocaleTimeString(),
              sha256_hash: f.sha256_hash || 'unavailable',
              summary: f.summary || `Air-gapped generated deliverable: ${f.filename}`,
              key_metrics: f.key_metrics || [
                { label: 'Format', value: type.toUpperCase() },
                { label: 'Status', value: f.verification_status || 'PENDING_STAGE_1' },
              ],
              // Only ever populated from a server-supplied field.
              sop_citations: Array.isArray(f.sop_citations) ? f.sop_citations : []
            };
          });

          set({ deliverables: diskItems });
        }
      }
    } catch (e) {
      console.warn('[useDeliverableStore] Auto-sync disk deliverables fallback:', e);
    }
  },

  downloadDeliverable: async (id: string) => {
    const item = get().deliverables.find((d) => d.id === id);
    if (!item) return;

    try {
      const res = await apiFetch(`/api/files/download/${encodeURIComponent(item.id || item.filename)}`);
      if (res.ok) {
        const blob = await res.blob();
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = item.filename;
        a.click();
        URL.revokeObjectURL(url);
        return;
      }
    } catch {
      // Fallback
    }

    const sanitizedFilename = item.filename.replace(/[^a-zA-Z0-9._-]/g, '_');
    console.warn(`[useDeliverableStore] Backend unavailable. Cannot download ${sanitizedFilename}.`);
  }
}));