"""
One-shot data migration: XAMPP MySQL/MariaDB -> PostgreSQL.

Copies every application table from the configured MySQL source into the
configured PostgreSQL target. The PostgreSQL schema is created first by
`backend.db.init_db()`, so only rows are moved here.

Safety properties:
  * Read-only against the MySQL source. Nothing is dropped or altered there.
  * Runs in one transaction per table on PostgreSQL; a failure rolls back that
    table rather than leaving it half-populated.
  * Verifies the row count after every table and reports a mismatch loudly.
  * Refuses to run unless the target tables already exist, so it can never
    invent its own schema.
  * Does not copy primary keys. Identity columns are regenerated in insertion
    order so the original ordering is preserved without colliding with the
    target's identity sequence.

Usage:
    python scripts/migrate_mysql_to_postgres.py --dry-run     # report only
    python scripts/migrate_mysql_to_postgres.py               # perform
    python scripts/migrate_mysql_to_postgres.py --truncate   # clear target first

Source/target come from the environment (see .env):
    MYSQL_HOST / MYSQL_PORT / MYSQL_USER / MYSQL_PASSWORD / MYSQL_DB
    PGHOST / PGPORT / PGUSER / PGPASSWORD / PGDATABASE
"""
import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

# Tables in dependency-free order; each is copied independently.
TABLES = [
    "messages",
    "chat_summaries",
    "files",
    "feedback_reports",
    "chat_channels",
    "channel_members",
    "channel_messages",
    "user_activity_logs",
]

# Columns that must not be copied verbatim.
#   id         - identity column, regenerated by the target
#   is_important - MySQL TINYINT(1) 0/1 must become a real PostgreSQL boolean
SKIP_COLUMNS = {"id"}
BOOL_COLUMNS = {"is_important"}


def load_env():
    """Loads repo-root .env into os.environ without overwriting real values."""
    env_path = Path(__file__).resolve().parent.parent / ".env"
    if not env_path.is_file():
        return
    for raw in env_path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key, value = key.strip(), value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


def connect_mysql():
    import pymysql

    return pymysql.connect(
        host=os.getenv("MYSQL_HOST", "127.0.0.1"),
        port=int(os.getenv("MYSQL_PORT", "3306")),
        user=os.getenv("MYSQL_USER", "root"),
        password=os.getenv("MYSQL_PASSWORD", ""),
        database=os.getenv("MYSQL_DB", "sih_sovereign_ai"),
        charset="utf8mb4",
        cursorclass=pymysql.cursors.DictCursor,
    )


def connect_postgres():
    import psycopg

    return psycopg.connect(
        host=os.getenv("PGHOST", os.getenv("PG_HOST", "127.0.0.1")),
        port=int(os.getenv("PGPORT", os.getenv("PG_PORT", "5432"))),
        user=os.getenv("PGUSER", os.getenv("PG_USER", "postgres")),
        password=os.getenv("PGPASSWORD", os.getenv("PG_PASSWORD", "postgres")),
        dbname=os.getenv("PGDATABASE", os.getenv("PG_DB", "sih_sovereign_ai")),
    )


def source_columns(mysql_cur, table):
    cur = mysql_cur.execute(f"SHOW COLUMNS FROM `{table}`")
    return [r["Field"] for r in mysql_cur.fetchall()]


def target_exists(pg_cur, table):
    pg_cur.execute(
        "SELECT 1 FROM information_schema.tables "
        "WHERE table_schema = current_schema() AND table_name = %s",
        (table,),
    )
    return pg_cur.fetchone() is not None


def copy_table(mysql_cur, pg_conn, table, dry_run, truncate):
    if not target_exists(pg_cur, table):
        print(f"  SKIP  {table}: target table does not exist (run init_db first)")
        return 0

    cols = source_columns(mysql_cur, table)
    copy_cols = [c for c in cols if c not in SKIP_COLUMNS]
    if not copy_cols:
        print(f"  SKIP  {table}: no copyable columns")
        return 0

    mysql_cur.execute(f"SELECT * FROM `{table}`")
    rows = mysql_cur.fetchall()
    src_count = len(rows)

    if src_count == 0:
        print(f"  OK    {table}: source empty, nothing to copy")
        return 0

    if dry_run:
        print(f"  WOULD {table}: {src_count} row(s), columns: {', '.join(copy_cols)}")
        return src_count

    if truncate:
        with pg_conn.cursor() as c:
            c.execute(f'TRUNCATE TABLE "{table}"')

    col_list = ", ".join(f'"{c}"' for c in copy_cols)
    placeholders = ", ".join(["%s"] * len(copy_cols))

    # ON CONFLICT DO NOTHING makes a re-run idempotent for tables whose primary
    # key is natural (files, chat_summaries, chat_channels, channel_members).
    natural_key = {
        "files": "file_id",
        "chat_summaries": "chat_id",
        "chat_channels": "id",
        "channel_members": None,  # composite
    }.get(table)

    conflict_clause = ""
    if natural_key:
        conflict_clause = f'ON CONFLICT ("{natural_key}") DO NOTHING'
    elif table == "channel_members":
        conflict_clause = 'ON CONFLICT ("channel_id", "username") DO NOTHING'

    insert_sql = (
        f'INSERT INTO "{table}" ({col_list}) VALUES ({placeholders}) '
        f"{conflict_clause}"
    )

    inserted = 0
    with pg_conn.cursor() as c:
        for row in rows:
            values = []
            for col in copy_cols:
                val = row.get(col)
                if col in BOOL_COLUMNS and val is not None:
                    val = bool(val)
                values.append(val)
            c.execute(insert_sql, tuple(values))
            inserted += 1

    # Verify: the target count must be at least what we just inserted.
    with pg_conn.cursor() as c:
        c.execute(f'SELECT COUNT(*) AS n FROM "{table}"')
        after = c.fetchone()["n"]

    status = "OK   " if after >= src_count else "WARN "
    print(
        f"  {status} {table}: copied {inserted} row(s); "
        f"source={src_count} target_now={after}"
    )
    if after < src_count:
        print(f"        WARNING: target has fewer rows than the source for {table}")
    return inserted


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="report row counts without writing anything")
    parser.add_argument("--truncate", action="store_true",
                        help="TRUNCATE each target table before copying")
    args = parser.parse_args()

    load_env()

    print("=" * 68)
    print("AEGIS AI  |  MySQL -> PostgreSQL data migration")
    print("=" * 68)
    print(f"  source : MySQL {os.getenv('MYSQL_HOST','127.0.0.1')}:"
          f"{os.getenv('MYSQL_PORT','3306')}/{os.getenv('MYSQL_DB','sih_sovereign_ai')}")
    print(f"  target : PostgreSQL {os.getenv('PGHOST','127.0.0.1')}:"
          f"{os.getenv('PGPORT','5432')}/{os.getenv('PGDATABASE','sih_sovereign_ai')}")
    print(f"  mode   : {'DRY RUN (no writes)' if args.dry_run else 'LIVE'}")
    print()

    try:
        mysql_conn = connect_mysql()
    except Exception as exc:
        print(f"ERROR: cannot reach the MySQL source: {exc}")
        return 2
    try:
        pg_conn = connect_postgres()
    except Exception as exc:
        print(f"ERROR: cannot reach the PostgreSQL target: {exc}")
        mysql_conn.close()
        return 2

    total = 0
    try:
        with mysql_conn.cursor() as mysql_cur, pg_conn.cursor() as pg_cur:
            for table in TABLES:
                try:
                    total += copy_table(
                        mysql_cur, pg_conn, table, args.dry_run, args.truncate
                    )
                except Exception as exc:
                    pg_conn.rollback()
                    print(f"  FAIL  {table}: {type(exc).__name__}: {exc}")
        if not args.dry_run:
            pg_conn.commit()
    finally:
        mysql_conn.close()
        pg_conn.close()

    print()
    print(f"{'Would copy' if args.dry_run else 'Copied'}: {total} row(s) across "
          f"{len(TABLES)} table(s)")
    if args.dry_run:
        print("Re-run without --dry-run to perform the migration.")
    else:
        print("Migration complete. Start the backend with AEGIS_DB_DRIVER=postgres.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
